### PR TITLE
Font Restructing

### LINKED ISSUE #1: collab server bundle module not found
Thank you so much! This is wonderful. Thank you for maintaining it.

Sorry, I am quite unexperienced with node js.
I wish to get the collaborations module working. I have already got webserver okay. But the collab server cannot run properly:
```
ted.chou@IITPC20-0109 prosemirror12 % python run_collab_server.py 
================================================================================
PORT=3002 IP=192.168.1.2 node servers/collab/run_licit_collab_server.bundle.js
================================================================================
internal/modules/cjs/loader.js:896
  throw err;
  ^

Error: Cannot find module '/Applications/MAMP/htdocs/prosemirror12/servers/collab/run_licit_collab_server.bundle.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:893:15)
    at Function.Module._load (internal/modules/cjs/loader.js:743:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

```
Could you guide me?
Thank you!.

### PR DESCRIPTION
**Pull request by firmusoft**
1. FIX: #1 - collab server bundle module not found.
2. Restructed fonts so that it is no more scatterred.
3. Katex & Mathquill Fonts are now used from the node modules instead of addtional copy at source directory.
4. Fonts were not packed by the npm commands.

### CODE REVIEW

File: src/ui/renderLaTeXAsHTML.js [hunk 1]
```diff
@@ -21,9 +20,9 @@ const CSS_FONT = 'KaTeX_Main';
 (async function() {
```
Comment (melgish) [inline src/ui/renderLaTeXAsHTML.js:20]: Is this function doing anything anymore?  Can it be removed?

**Review by melgish — APPROVED** [review]
